### ISSUE TITLE
官方还未开源代码吗?

### ISSUE THREAD

**Issue by MARD1NO** [mayf1y/dynet#1]
您好想问下这份代码出处，是你自己根据论文复现的还是官方在别的地方有相关开源？

**Comment by mayf1y** [comment]
自己根据论文复现的哈


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mardino"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 下午2:18
收件人:&nbsp;"mayf1y/dynet"<dynet@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mayf1y/dynet] 官方还未开源代码吗? (#1)





 
您好想问下这份代码出处，是你自己根据论文复现的还是官方在别的地方有相关开源？
